package fr.ho2s.holmes.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.11
 * 2016-11-03T08:57:40.493+01:00
 * Generated source version: 3.0.11
 * 
 */
@WebService(targetNamespace = "http://ws.holmes.ho2s.fr/", name = "HolmesServiceFrench")
@XmlSeeAlso({ObjectFactory.class})
public interface HolmesServiceFrench {

    @WebMethod
    @Action(input = "http://ws.holmes.ho2s.fr/HolmesServiceFrench/analyzeRequest", output = "http://ws.holmes.ho2s.fr/HolmesServiceFrench/analyzeResponse")
    @RequestWrapper(localName = "analyze", targetNamespace = "http://ws.holmes.ho2s.fr/", className = "fr.ho2s.holmes.ws.Analyze")
    @ResponseWrapper(localName = "analyzeResponse", targetNamespace = "http://ws.holmes.ho2s.fr/", className = "fr.ho2s.holmes.ws.AnalyzeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public fr.ho2s.holmes.ws.HolmesOutput analyze(
        @WebParam(name = "text", targetNamespace = "")
        java.lang.String text
    );

    @WebMethod
    @Action(input = "http://ws.holmes.ho2s.fr/HolmesServiceFrench/parseRequest", output = "http://ws.holmes.ho2s.fr/HolmesServiceFrench/parseResponse")
    @RequestWrapper(localName = "parse", targetNamespace = "http://ws.holmes.ho2s.fr/", className = "fr.ho2s.holmes.ws.Parse")
    @ResponseWrapper(localName = "parseResponse", targetNamespace = "http://ws.holmes.ho2s.fr/", className = "fr.ho2s.holmes.ws.ParseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public fr.ho2s.holmes.ws.HolmesOutput parse(
        @WebParam(name = "text", targetNamespace = "")
        java.lang.String text
    );
}
