
package fr.ho2s.holmes.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.11
 * 2016-11-03T08:57:40.146+01:00
 * Generated source version: 3.0.11
 * 
 */
public final class HolmesServiceFrench_HolmesServiceFrenchPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.holmes.ho2s.fr/", "HolmesServiceFrenchService");

    private HolmesServiceFrench_HolmesServiceFrenchPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HolmesServiceFrenchService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HolmesServiceFrenchService ss = new HolmesServiceFrenchService(wsdlURL, SERVICE_NAME);
        HolmesServiceFrench port = ss.getHolmesServiceFrenchPort();  
        
        {
        System.out.println("Invoking analyze...");
        java.lang.String _analyze_text = "";
        fr.ho2s.holmes.ws.HolmesOutput _analyze__return = port.analyze(_analyze_text);
        System.out.println("analyze.result=" + _analyze__return);


        }
        {
        System.out.println("Invoking parse...");
        java.lang.String _parse_text = "";
        fr.ho2s.holmes.ws.HolmesOutput _parse__return = port.parse(_parse_text);
        System.out.println("parse.result=" + _parse__return);


        }

        System.exit(0);
    }

}
