package fr.ho2s.holmes.ner.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.11
 * 2016-10-26T21:35:46.061+02:00
 * Generated source version: 3.0.11
 * 
 */
@WebServiceClient(name = "HolmesNERServiceFrenchService", 
                  wsdlLocation = "file:/C:/Users/dhouib/Desktop/SMILK_project_devpt/RelationExtractionSMILK/src/main/resources/HolmesNERServiceFrench.wsdl",
                  targetNamespace = "http://ws.ner.holmes.ho2s.fr/") 
public class HolmesNERServiceFrenchService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.ner.holmes.ho2s.fr/", "HolmesNERServiceFrenchService");
    public final static QName HolmesNERServiceFrenchPort = new QName("http://ws.ner.holmes.ho2s.fr/", "HolmesNERServiceFrenchPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/dhouib/Desktop/SMILK_project_devpt/RelationExtractionSMILK/src/main/resources/HolmesNERServiceFrench.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HolmesNERServiceFrenchService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/dhouib/Desktop/SMILK_project_devpt/RelationExtractionSMILK/src/main/resources/HolmesNERServiceFrench.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HolmesNERServiceFrenchService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HolmesNERServiceFrenchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HolmesNERServiceFrenchService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HolmesNERServiceFrenchService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HolmesNERServiceFrenchService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HolmesNERServiceFrenchService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns HolmesNERServiceFrench
     */
    @WebEndpoint(name = "HolmesNERServiceFrenchPort")
    public HolmesNERServiceFrench getHolmesNERServiceFrenchPort() {
        return super.getPort(HolmesNERServiceFrenchPort, HolmesNERServiceFrench.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HolmesNERServiceFrench
     */
   /* @WebEndpoint(name = "HolmesNERServiceFrenchPort")
    public HolmesNERServiceFrench getHolmesNERServiceFrenchPort(HolmesNERServiceFrenchService features) {
        return super.getPort(HolmesNERServiceFrenchPort, HolmesNERServiceFrench.class, features);
    }*/

}
