package fr.ho2s.holmes.ner.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.11
 * 2016-10-26T21:35:46.049+02:00
 * Generated source version: 3.0.11
 * 
 */
@WebService(targetNamespace = "http://ws.ner.holmes.ho2s.fr/", name = "HolmesNERServiceFrench")
@XmlSeeAlso({ObjectFactory.class})
public interface HolmesNERServiceFrench {

    @WebMethod
    @Action(input = "http://ws.ner.holmes.ho2s.fr/HolmesNERServiceFrench/parseRequest", output = "http://ws.ner.holmes.ho2s.fr/HolmesNERServiceFrench/parseResponse")
    @RequestWrapper(localName = "parse", targetNamespace = "http://ws.ner.holmes.ho2s.fr/", className = "fr.ho2s.holmes.ner.ws.Parse")
    @ResponseWrapper(localName = "parseResponse", targetNamespace = "http://ws.ner.holmes.ho2s.fr/", className = "fr.ho2s.holmes.ner.ws.ParseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<fr.ho2s.holmes.ner.ws.CompactNamedEntity> parse(
        @WebParam(name = "text", targetNamespace = "")
        java.lang.String text
    );
}
